// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtJJxcbcbv8Y-JiQnfZP7e_GZ6LLL78VY',
    appId: '1:69433430524:web:ac98581f828579d96aa279',
    messagingSenderId: '69433430524',
    projectId: 'tourguide-firebase',
    authDomain: 'tourguide-firebase.firebaseapp.com',
    storageBucket: 'tourguide-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf-uyKpRcaTsQclO91D0fv7AgcEBAAUb8',
    appId: '1:69433430524:android:40f52d44777c593d6aa279',
    messagingSenderId: '69433430524',
    projectId: 'tourguide-firebase',
    storageBucket: 'tourguide-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8X23vQAAxM5DUNqGXSpKrHHR99uYn33M',
    appId: '1:69433430524:ios:380acdf793fd2d496aa279',
    messagingSenderId: '69433430524',
    projectId: 'tourguide-firebase',
    storageBucket: 'tourguide-firebase.appspot.com',
    iosBundleId: 'com.robertMichelsDigitalMedia.tourguideApp',
  );
}
