// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM72gUAVb8bkpEv20TQ7-WkBaEzDAc8Cs',
    appId: '1:1076620464241:web:dc560070ea2842d2a44bd0',
    messagingSenderId: '1076620464241',
    projectId: 'tourguideapp-45a06',
    authDomain: 'tourguideapp-45a06.firebaseapp.com',
    storageBucket: 'tourguideapp-45a06.appspot.com',
    measurementId: 'G-DVPTQGSN9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8jDV22Bj1Lri2QrKmxCSPxHd8J9dxkMM',
    appId: '1:1076620464241:android:615de7760d0c4d6da44bd0',
    messagingSenderId: '1076620464241',
    projectId: 'tourguideapp-45a06',
    storageBucket: 'tourguideapp-45a06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvhryptRU4d9PfI_iJyunsxGHKUtPTBik',
    appId: '1:1076620464241:ios:7c989ca654f8f857a44bd0',
    messagingSenderId: '1076620464241',
    projectId: 'tourguideapp-45a06',
    storageBucket: 'tourguideapp-45a06.appspot.com',
    iosClientId: '1076620464241-acjn41je8pp9c9sgl07ftimgf3sr1ik4.apps.googleusercontent.com',
    iosBundleId: 'com.robertMichelsDigitalMedia.tourguideApp',
  );
}
