# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build and deploy to Open Testing track"
  lane :deploy do

    # Build the appbundle
    # gradle(task: "bundle", build_type: "Release")
    sh "flutter build appbundle"

    # Generate the changelog from Git commits
    changelog = changelog_from_git_commits(
      commits_count: 1
    )

    # Define the version code (this needs to match your APK/AAB version code)
    latest_version_code = (
      google_play_track_version_codes(
        track: "beta",
      )
    ).max
    next_version_code = latest_version_code + 1

    # Define the path for the changelog file
    changelog_directory = "fastlane/metadata/android/en-US/changelogs"
    FileUtils.mkdir_p(changelog_directory)
    changelog_file_path = "#{changelog_directory}/#{next_version_code}.txt"

    # Write the changelog to the file
    File.write(changelog_file_path, changelog)

    # Upload the appbundle to the Play Store - note this automatically reads changelogs from the changelog directory
    upload_to_play_store(
      json_key: "app/google-play-key.json",
      track: 'beta',
      aab: "../build/app/outputs/bundle/release/app-release.aab"
    )
  end

  # desc "Runs all the tests"
  # lane :test do
  #   gradle(task: "test")
  # end

  # desc "Submit a new Beta Build to Crashlytics Beta"
  # lane :beta do
  #   gradle(task: "clean assembleRelease")
  #   crashlytics
  
  #   # sh "your_script.sh"
  #   # You can also use other beta testing services here
  # end

  # desc "Deploy a new version to the Google Play"
  # lane :deploy do
  #   gradle(task: "clean assembleRelease")
  #   upload_to_play_store
  # end
end
